import argparse


def add_common_args(argparser):
    argparser.add_argument("--gpu", type=int, default=0, help="GPU device ID.")
    argparser.add_argument("--n-runs", type=int, default=3, help="number of runs")
    argparser.add_argument("--n-epochs", type=int, default=1000, help="number of epochs")
    argparser.add_argument("--lr", type=float, default=0.005, help="learning rate")
    argparser.add_argument("--wd", type=float, default=5e-4, help="weight decay")
    argparser.add_argument("--dropout", type=float, default=0.5)
    argparser.add_argument("--n-hidden", type=int, default=128)
    argparser.add_argument("--n-layers", type=int, default=2)
    argparser.add_argument("--n-heads", type=int, default=3)
    argparser.add_argument("--gpu_mem", type=int, default=0)
    argparser.add_argument("--graph_path", type=str, default=None)
    argparser.add_argument("--seed", type=int, default=42)
    argparser.add_argument("--early_stop_patience", type=int, default=100)
    argparser.add_argument("--eval_steps", type=int, default=1)
    argparser.add_argument("--log_every", type=int, default=10)
    argparser.add_argument("--verbose", type=int, default=1)
    argparser.add_argument("--data_name", type=str, default="")
    argparser.add_argument("--output_file", type=str, default="")
    argparser.add_argument("--label_smoothing", type=float, default=0.1)
    argparser.add_argument("--average", type=str, default="macro")
    argparser.add_argument("--min_lr", type=float, default=1e-5)
    argparser.add_argument("--save_checkpoints", type=int, default=0)
    argparser.add_argument("--checkpoint_dir", type=str, default="")
    argparser.add_argument("--checkpoint_metric", type=str, default="val_acc")


def add_topscan_args(argparser):
    argparser.add_argument("--text_feature", type=str, default="")
    argparser.add_argument("--visual_feature", type=str, default="")
    argparser.add_argument("--cross_graph_path", type=str, default="")
    argparser.add_argument("--gnn_type", type=str, default="GraphSAGE",
                           choices=["GCN", "GAT", "GraphSAGE", "RevGAT", "SGC"])
    argparser.add_argument("--aggregator", type=str, default="mean")
    argparser.add_argument("--use_attn_dst", type=int, default=1)
    argparser.add_argument("--use_symmetric_norm", type=int, default=1)
    argparser.add_argument("--attn_drop", type=float, default=0.1)
    argparser.add_argument("--edge_drop", type=float, default=0.1)
    argparser.add_argument("--input_dropout", type=float, default=0.0)
    argparser.add_argument("--alpha", type=float, default=0.1)
    argparser.add_argument("--k_ps", type=int, default=10)
    argparser.add_argument("--bias", type=int, default=1)
    argparser.add_argument("--k", type=int, default=2)
    argparser.add_argument("--warmup_epochs", type=int, default=0)
    argparser.add_argument("--cma_num_heads", type=int, default=4)
    argparser.add_argument("--cma_head_dim", type=int, default=32)
    argparser.add_argument("--cma_dropout", type=float, default=0.2)
    argparser.add_argument("--cma_attn_dropout", type=float, default=0.2)
    argparser.add_argument("--cma_norm_by", type=str, default="dst", choices=["src", "dst"])
    argparser.add_argument("--warmup_fusion", type=str, default="concat_absdiff",
                           choices=["concat", "concat_absdiff", "residual"])
    argparser.add_argument("--warmup_alpha", type=float, default=0.5)
    argparser.add_argument("--checkpoint_prefix", type=str, default="")
    argparser.add_argument("--grid_search", type=int, default=0)
    argparser.add_argument("--grid_gnn_types", type=str, default="GraphSAGE,RevGAT")
    argparser.add_argument("--grid_layers", type=str, default="2,3")
    argparser.add_argument("--grid_hidden_units", type=str, default="128,256")
    argparser.add_argument("--grid_lrs", type=str, default="0.005,0.01")
    argparser.add_argument("--grid_dropouts", type=str, default="0.3,0.5")
    argparser.add_argument("--grid_backbones", type=str, default="")
    argparser.add_argument("--grid_fusions", type=str, default="concat_absdiff")
    argparser.add_argument("--grid_residual_alphas", type=str, default="0.5")
    argparser.add_argument("--grid_cma_num_heads", type=str, default="4,8")
    argparser.add_argument("--grid_cma_head_dims", type=str, default="32")
    argparser.add_argument("--grid_cma_attn_dropouts", type=str, default="0.1,0.2")
    argparser.add_argument("--grid_cma_norm_bys", type=str, default="src,dst")
    argparser.add_argument("--policy_mode", type=str, default="on", choices=["on", "off"])
    argparser.add_argument("--policy_select_mode", type=str, default="top_fraction",
                           choices=["top_fraction", "hard"])
    argparser.add_argument("--policy_cross_score", type=str, default="geometric",
                           choices=["geometric", "arithmetic", "cross", "text", "image"])
    argparser.add_argument("--enhance_cross_graph", type=int, default=1)
    argparser.add_argument("--candidate_cache_dir", type=str, default="")
    argparser.add_argument("--candidate_cache_key", type=str, default="")
    argparser.add_argument("--rebuild_candidate_cache", type=int, default=0)
    argparser.add_argument("--policy_k", type=int, default=2)
    argparser.add_argument("--policy_q", type=float, default=0.95)
    argparser.add_argument("--policy_top_m", type=int, default=2)
    argparser.add_argument("--policy_top_p", type=float, default=0.15)
    argparser.add_argument("--use_edge_weight_in_backbone", type=int, default=0)
    argparser.add_argument("--edge_weight_alpha", type=float, default=0.5)
    argparser.add_argument("--use_enhanced_graph_in_backbone", type=int, default=0)
    argparser.add_argument("--grid_policy_ks", type=str, default="2,3")
    argparser.add_argument("--grid_policy_qs", type=str, default="0.90,0.95,0.97")
    argparser.add_argument("--grid_policy_top_ms", type=str, default="1,2,3")
    argparser.add_argument("--grid_policy_top_ps", type=str, default="0.10,0.15")
